- hosts: dqcdevqat
  become: yes
  become_method: sudo
  connection: ssh

  tasks:
  - name: Un-Install collectd
    yum:
      name: collectd
      state: absent
    register: result
  - debug: var=result

  - copy:
     src: /etc/ansible/roles/ucm_collectd/collectd-5.7.1-2.el7.x86_64.rpm
     dest: /root/collectd-5.7.1-2.el7.x86_64.rpm
     owner: root
     group: root
     mode: 0644

  - name: Install collectd
    yum:
      name: /root/collectd-5.7.1-2.el7.x86_64.rpm
      state: present
    register: result
  - debug: var=result

  - name: Install collectd-exporter
    yum:
      name: http://artifactory.corporate.t-mobile.com/artifactory/ucm-yum-release-local/collectd-exporter-1.0.8-1.el7.x86_64.rpm
      state: present
    register: result
  - debug: var=result

  - name: Restart collectd
    service:
      name: collectd
      state: started
    register: result
  - debug: var=result

  - name: Enable service collectd
    systemd:
      name: collectd
      enabled: yes
    register: result
  - debug: var=result
